// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:83c365d9-9336-42c1-b905-5e9eb8129d17",
    "aws_cognito_region": "eu-central-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "17bbcc8960fe4f05a7b71f7658aa72a9",
    "aws_mobile_analytics_app_region": "eu-central-1"
};


export default awsmobile;
